name: commit-and-push
author: alejandrohdezma
description: >
  Creates a new commit with current changes and push them
  to the selected branch using the GitHub Actions user

inputs:
  branch:
    description: >
      Git branch name, where changes should be pushed too.
      Required if Action is not used on the `pull_request` event
    required: false
    default: ${{ github.head_ref }}
  message:
    description: Message for the new commit
    required: true

runs:
  using: composite
  steps:
    - name: Create commit with current changes and push it to ${{ inputs.branch }}
      shell: bash
      run: ${{ github.action_path }}/commit-and-push.sh
      env:
        GIT_NAME: github-actions
        GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_MESSAGE: ${{ inputs.message }}
        GIT_BRANCH: ${{ inputs.branch }}
