name: labeler
author: alejandrohdezma
description: Auto-label PRs based on branch/size

inputs:
  sizes:
    description: Number of changes for each size as an integer comma-separated array
    default: 2000,1000,500,100,50,10
    required: false

runs:
  using: composite
  steps:
    - name: Label PR based on branch
      shell: bash
      run: ${{ github.action_path }}/label-pr-based-on-branch.sh
      env:
        PR: ${{ github.event.pull_request.html_url }}
        REF: ${{ github.event.pull_request.head.ref }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Label PR based on size
      shell: bash
      run: ${{ github.action_path }}/label-pr-based-on-size.sh
      env:
        PR: ${{ github.event.pull_request.html_url }}
        CHANGES: ${{ github.event.pull_request.additions }} + ${{ github.event.pull_request.deletions }}
        SIZES: ${{ inputs.sizes }}
        GITHUB_TOKEN: ${{ github.token }}
