name: scala
author: alejandrohdezma
description: Executes a SBT task on the provided JVM

inputs:
  github-token:
    description: A valid GitHub Token. Will be handed to the SBT task as GITHUB_TOKEN env variable
    required: false
    default: ${{ github.token }}
  jvm:
    description: The JVM to install
    required: false
    default: adopt:1.11
  task:
    description: The SBT task to run
    required: false
    default: test

runs:
  using: composite
  steps:
    - name: Enable Coursier cache
      uses: coursier/cache-action@0cdf229a86211e64f9a576ee6c00cdf662f2554d # v6.3

    - name: Setup Coursier
      uses: laughedelic/coursier-setup@7c7046155768b6734098d98f10a94cf2616e2669 # v1.1.2
      with:
        jvm: ${{ inputs.jvm }}
        apps: sbt

    - name: Run SBT task
      shell: bash
      run: sbt ${{ inputs.task }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
