name: scala
author: alejandrohdezma
description: Executes a SBT task on the provided JVM

inputs:
  github-token:
    description: A valid GitHub Token. Will be handed to the SBT task as GITHUB_TOKEN env variable
    required: false
    default: ${{ github.token }}
  jvm:
    description: The JVM to install
    required: false
    default: liberica:11
  task:
    description: The SBT task to run
    required: false
    default: test

runs:
  using: composite
  steps:
    - name: Enable Coursier cache
      uses: coursier/cache-action@38fe9893c588c871ecc973df9609c7378a27a759 # v6.3.2

    - name: Setup Coursier
      uses: laughedelic/coursier-setup@f6d7bf57ed5e0e3715c6261041f2169826c34c1a # v1.2
      with:
        jvm: ${{ inputs.jvm }}
        apps: sbt

    - name: Run SBT task
      shell: bash
      run: sbt ${{ inputs.task }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
