# This workflow contains the list of GitHub actions used accross the different
# composite actions of this repository. Dependabot doesn't allow to update the
# versions inside composite `action.yml` files, so we trigger the update on this
# file and then propagate it to the composite actions using the
# `alejandrohdezma/actions/update-github-actions` GitHub Action.

name: List of used GitHub Actions inside composite

on:
  repository_dispatch:

permissions: read-all

jobs:
  list-of-used-github-actions-so-dependabot-updates-them:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: coursier/cache-action@0cdf229a86211e64f9a576ee6c00cdf662f2554d # v6.3.1

      - uses: laughedelic/coursier-setup@f6d7bf57ed5e0e3715c6261041f2169826c34c1a # v1.1.2

